site_name: たらちゃんの知恵箱
site_author: 'Tarachan'
repo_url: https://github.com/Tarachan/Tarachans-tech-box
site_url: https://Tarachan.github.io/Tarachans-tech-box/

pages:
    - Home:    index.md
    - Maya:    Maya/maya.md
    - Houdini: Houdini/houdini.md
    - Blender: Blender/blender.md
    - Nuke:    Nuke/nuke.md
    - Python:  Python/python.md
    - PySide:  PySide/pyside.md
    - Test: 
        - MkDocs 書き方: MkDocs/mkdocs.md

theme:
  name: material
  language: 'ja'
  feature:
    tabs: true
  palette:
   #primary: 'Red'
   #accent: 'Red'

extra:
  search:
    language: 'ja'

markdown_extensions:
  - codehilite:
      linenums: true
      #use_pygments: true
      #noclasses: true
      #pygments_style: monokai

extra_css:
  - "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  - "css/custom.css"